### ISSUE TITLE
Replace the deprecated serde_yaml dependency

### ISSUE THREAD

**Issue by hko-s** [carapace-sh/carapace-spec-clap#216]
### Request

The serde_yaml dependency has been deprecated upstream

### Proposed solution

One possible alternative is the serde_yml crate, which I believe is pretty much a drop-in replacement.

## Polar

<a href="https://polar.sh/carapace-sh/carapace-spec-clap/issues/216">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace-spec-clap/issues/216/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace-spec-clap/issues/216/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Thanks for letting me now. There's no rush on this so let's see how thing develop with `serde_yml`.

**Comment by wiktor-k** [comment]
> Thanks for letting me now. There's no rush on this so let's see how thing develop with `serde_yml`.

Hmm... would you be open for a submission that migrates to the non deprecated one or not? I'm happy to send a PR if that's possible.

(My motivation is your crate is a dependency of my own crate `clap_allgen` and deprecated deps can have issues as time progresses)

Thanks for your time! 👋

**Comment by hko-s** [comment]
> Thanks for letting me now. There's no rush on this so let's see how thing develop with `serde_yml`.

Thank you for the update!

Switching to a maintained alternative to `serde_yaml` sooner rather than later would be helpful for me:
Unfortunately, the `serde_yaml` dependency makes projects that use `carapace-sh` harder to package for distributions like Debian (this is what prompted me to open this ticket).

But then of course software engineering-life is full of tradeoffs and mutually contradictory goals, so I understand if you prefer to move more slowly.

**Comment by rsteube** [comment]
Ah, ok then. I don't mind switching.
`serde_yml` does look to be the most promising fork, so let's go with it.

**Comment by rsteube** [comment]
So [serde_yml](https://github.com/sebastienrousseau/serde_yml) adds unnecessary quotes to map keys:
```diff
-  -V, --version: Print version
+  '-V, --version': Print version
```

Which is something i'd like to avoid.
And there [some aspects](https://users.rust-lang.org/t/serde-yaml-deprecation-alternatives) to it that don't make me put my trust in it (for now).
Issue tracker also isn't active on the project so it's not clear if the project is really meant for public use.

[serde_yaml_ng] on the other hand at least [announced to be open for external contributions](https://users.rust-lang.org/t/serde-yaml-deprecation-alternatives/108868/46).

It's unclear where things go with yaml support in rust which is why i was planning to wait a little.
I'm fine with using [serde_yaml_ng] for now, but be aware that all we do is getting rid of a "deprecated" notice on a project which is otherwise completely fine.

[serde_yaml_ng]:https://github.com/acatton/serde-yaml-ng

**Comment by hko-s** [comment]
Understood (and your perspectives make sense to me).

Thank you for doing this work already now, even though the medium term future of yaml in Rust looks unclear indeed!
